# **Proyecto Final Estadistica**

Integrantes: Kevin Yamid Agreda Pianda\
             Santiago

# **I. Reconocimiento de Datos**

# **1. Importacion de librerias**

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import math pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import math

# **2. Lectura del Archivo Clientes**

In [5]:
archivo_clientes = r'C:\Users\Developer\Documents\Universida Cooperativa\Segundo Semestre Homologacion\Estadisitica\Proyecto Final - Estadistica\Data-Sucia\base_datos_restaurantes_USA_v2.csv'
df_clientes = pd.read_csv(archivo_clientes)

## **3. Verificación de información de dataset**

In [3]:
display (df_clientes.head()) 
display (df_clientes.info())
display (df_clientes.describe())

,id_persona,nombre,apellido,edad,genero,ciudad_residencia,estrato_socioeconomico,frecuencia_visita,promedio_gasto_comida,ocio,consume_licor,preferencias_alimenticias,membresia_premium,telefono_contacto,correo_electronico,tipo_de_pago_mas_usado,ingresos_mensuales
0,2550327378,Jackson,Gomez,31.0,Masculino,Miami,Alto,6,67.51,Sí,No,Vegetariano,Sí,(830)220-1926,NaN,Efectivo,6425
1,9446112038,Samantha,Soto,40.0,Femenino,Denver,Medio,2,44.92,Sí,Sí,Mariscos,No,881-476-1426,NaN,Efectivo,2374
2,3098363243,Terry,Adams,62.0,Femenino,Denver,Bajo,2,9.24,Sí,Sí,Vegetariano,No,NaN,diana74@example.net,Efectivo,1110
3,4013002847,James,Shannon,41.0,Masculino,Boston,Alto,5,30.74,Sí,Sí,Carnes,Sí,NaN,scottfrey@example.com,Tarjeta,6931
4,7372911048,Susan,Jones,49.0,Femenino,San Diego,Bajo,0,0.00,No,No,Carnes,No,243.248.8919,glassgary@example.org,Tarjeta,1350

<class 'pandas.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 17 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   id_persona                 30000 non-null  int64
 1   nombre                     30000 non-null  str
 2   apellido                   30000 non-null  str
 3   edad                       29899 non-null  float64
 4   genero                     30000 non-null  str
 5   ciudad_residencia          30000 non-null  str
 6   estrato_socioeconomico     30000 non-null  str
 7   frecuencia_visita          30000 non-null  int64
 8   promedio_gasto_comida      29855 non-null  float64
 9   ocio                       30000 non-null  str
 10  consume_licor              30000 non-null  str
 11  preferencias_alimenticias  28597 non-null  str
 12  membresia_premium          30000 non-null  str
 13  telefono_contacto          14834 non-null  str
 14  correo_electronico         14928 non-null  str
 15  tipo_de_pago_mas_usado     30000 non-null  str
 16  ingresos_mensuales         30000 non-null  int64
dtypes: float64(2), int64(3), str(12)
memory usage: 3.9 MB

None

,id_persona,edad,frecuencia_visita,promedio_gasto_comida,ingresos_mensuales
count,3.000000e+04,29899.000000,30000.000000,29855.000000,30000.000000
mean,5.504765e+09,49.665006,3.896133,32.603452,5389.755867
std,2.602799e+09,23.839550,2.741532,26.402601,4538.491728
min,1.000153e+09,-5.000000,-3.000000,0.000000,800.000000
25%,3.243617e+09,33.000000,2.000000,13.290000,1860.000000
50%,5.515865e+09,49.000000,4.000000,25.510000,3402.000000
75%,7.754426e+09,65.000000,5.000000,44.400000,7761.000000
max,9.999627e+09,300.000000,10.000000,149.970000,17999.000000

# **II. Limpieza de Datos**

## **1. Gestión de duplicados**

In [4]:
# Encontrar y borrar datos duplicados base clientes
df_clientes_mod = df_clientes.drop_duplicates(subset=['id_persona'], keep='first')
df_clientes_mod.info()

<class 'pandas.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 17 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   id_persona                 30000 non-null  int64
 1   nombre                     30000 non-null  str
 2   apellido                   30000 non-null  str
 3   edad                       29899 non-null  float64
 4   genero                     30000 non-null  str
 5   ciudad_residencia          30000 non-null  str
 6   estrato_socioeconomico     30000 non-null  str
 7   frecuencia_visita          30000 non-null  int64
 8   promedio_gasto_comida      29855 non-null  float64
 9   ocio                       30000 non-null  str
 10  consume_licor              30000 non-null  str
 11  preferencias_alimenticias  28597 non-null  str
 12  membresia_premium          30000 non-null  str
 13  telefono_contacto          14834 non-null  str
 14  correo_electronico         14928 non-null  str
 15  tipo_de_pago_mas_usado     30000 non-null  str
 16  ingresos_mensuales         30000 non-null  int64
dtypes: float64(2), int64(3), str(12)
memory usage: 3.9 MB

## **2. Categorizando para encontrar datos incoherentes**

In [5]:
df_clientes_mod['Rango_Edad'] = pd.cut(df_clientes_mod['edad'], bins=[-6, 0, 100, 300], labels=["Negativos", "Coherente", "Incoherente"])
edad_rango = df_clientes_mod.groupby('Rango_Edad').size() # Contando edad por rango 
print(edad_rango)

Rango_Edad
Negativos         97
Coherente      29692
Incoherente      110
dtype: int64

## **3. Transformación de datos negativos e incoherentes en vacíos**

In [4]:
df_clientes_mod['edad'] = pd.to_numeric(df_clientes_mod['edad'], errors='coerce') # Convierte edad en formato numero
df_clientes_mod.loc[(df_clientes_mod['edad']<0)|(df_clientes_mod['edad']>100),'edad']=np.nan

NameError: name 'df_clientes_mod' is not defined