# **Proyecto Final Estadistica**

Integrantes: Kevin Yamid Agreda Pianda\
             Santiago

# **I. Reconocimiento de Datos**

# **1. Importacion de librerias**

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import math

print("Librerías importadas correctamente")

Librerías importadas correctamente

## **2. Lectura del Archivo Clientes**

In [2]:
archivo_clientes = r'C:\Users\Developer\Documents\Universida Cooperativa\Segundo Semestre Homologacion\Estadisitica\Trabajo final\Proyecto_Final\Data-Sucia\base_datos_restaurantes_USA_v2.csv'
df_clientes = pd.read_csv(archivo_clientes)

## **3. Verificación de información de dataset**

In [3]:
display (df_clientes.head()) 
display (df_clientes.info())
display (df_clientes.describe())

,id_persona,nombre,apellido,edad,genero,ciudad_residencia,estrato_socioeconomico,frecuencia_visita,promedio_gasto_comida,ocio,consume_licor,preferencias_alimenticias,membresia_premium,telefono_contacto,correo_electronico,tipo_de_pago_mas_usado,ingresos_mensuales
0,2550327378,Jackson,Gomez,31.0,Masculino,Miami,Alto,6,67.51,Sí,No,Vegetariano,Sí,(830)220-1926,NaN,Efectivo,6425
1,9446112038,Samantha,Soto,40.0,Femenino,Denver,Medio,2,44.92,Sí,Sí,Mariscos,No,881-476-1426,NaN,Efectivo,2374
2,3098363243,Terry,Adams,62.0,Femenino,Denver,Bajo,2,9.24,Sí,Sí,Vegetariano,No,NaN,diana74@example.net,Efectivo,1110
3,4013002847,James,Shannon,41.0,Masculino,Boston,Alto,5,30.74,Sí,Sí,Carnes,Sí,NaN,scottfrey@example.com,Tarjeta,6931
4,7372911048,Susan,Jones,49.0,Femenino,San Diego,Bajo,0,0.00,No,No,Carnes,No,243.248.8919,glassgary@example.org,Tarjeta,1350

<class 'pandas.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 17 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   id_persona                 30000 non-null  int64
 1   nombre                     30000 non-null  str
 2   apellido                   30000 non-null  str
 3   edad                       29899 non-null  float64
 4   genero                     30000 non-null  str
 5   ciudad_residencia          30000 non-null  str
 6   estrato_socioeconomico     30000 non-null  str
 7   frecuencia_visita          30000 non-null  int64
 8   promedio_gasto_comida      29855 non-null  float64
 9   ocio                       30000 non-null  str
 10  consume_licor              30000 non-null  str
 11  preferencias_alimenticias  28597 non-null  str
 12  membresia_premium          30000 non-null  str
 13  telefono_contacto          14834 non-null  str
 14  correo_electronico         14928 non-null  str
 15  tipo_de_pago_mas_usado     30000 non-null  str
 16  ingresos_mensuales         30000 non-null  int64
dtypes: float64(2), int64(3), str(12)
memory usage: 3.9 MB

None

,id_persona,edad,frecuencia_visita,promedio_gasto_comida,ingresos_mensuales
count,3.000000e+04,29899.000000,30000.000000,29855.000000,30000.000000
mean,5.504765e+09,49.665006,3.896133,32.603452,5389.755867
std,2.602799e+09,23.839550,2.741532,26.402601,4538.491728
min,1.000153e+09,-5.000000,-3.000000,0.000000,800.000000
25%,3.243617e+09,33.000000,2.000000,13.290000,1860.000000
50%,5.515865e+09,49.000000,4.000000,25.510000,3402.000000
75%,7.754426e+09,65.000000,5.000000,44.400000,7761.000000
max,9.999627e+09,300.000000,10.000000,149.970000,17999.000000

# **II. Limpieza de Datos**

## **1. Gestión de duplicados**

In [4]:
# Encontrar y borrar datos duplicados base clientes
df_clientes_mod = df_clientes.drop_duplicates(subset=['id_persona'], keep='first')
df_clientes_mod.info()

<class 'pandas.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 17 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   id_persona                 30000 non-null  int64
 1   nombre                     30000 non-null  str
 2   apellido                   30000 non-null  str
 3   edad                       29899 non-null  float64
 4   genero                     30000 non-null  str
 5   ciudad_residencia          30000 non-null  str
 6   estrato_socioeconomico     30000 non-null  str
 7   frecuencia_visita          30000 non-null  int64
 8   promedio_gasto_comida      29855 non-null  float64
 9   ocio                       30000 non-null  str
 10  consume_licor              30000 non-null  str
 11  preferencias_alimenticias  28597 non-null  str
 12  membresia_premium          30000 non-null  str
 13  telefono_contacto          14834 non-null  str
 14  correo_electronico         14928 non-null  str
 15  tipo_de_pago_mas_usado     30000 non-null  str
 16  ingresos_mensuales         30000 non-null  int64
dtypes: float64(2), int64(3), str(12)
memory usage: 3.9 MB

## **2. Categorizando para encontrar datos incoherentes**

In [5]:
# Categorizando la edad para encontrar datos incoherentes
df_clientes_mod['Rango_Edad'] = pd.cut(df_clientes_mod['edad'], bins=[-6, 0, 100, 300], labels=["Negativos", "Coherente", "Incoherente"])
edad_rango = df_clientes_mod.groupby('Rango_Edad').size() # Contando edad por rango 
print(edad_rango)

# Categorizando la frecuencia de visita para encontrar datos incoherentes
df_clientes_mod['Rango_Frecuencia'] = pd.cut(df_clientes_mod['frecuencia_visita'], bins=[-6, -1, 10], labels=["Negativos", "Coherente"])
frecuencia_rango = df_clientes_mod.groupby('Rango_Frecuencia').size() # Contando frecuencia por rango
print(frecuencia_rango)

Rango_Edad
Negativos         97
Coherente      29692
Incoherente      110
dtype: int64
Rango_Frecuencia
Negativos     1547
Coherente    28453
dtype: int64

## **3. Transformación de datos negativos e incoherentes en vacíos**

In [6]:
df_clientes_mod['edad'] = pd.to_numeric(df_clientes_mod['edad'], errors='coerce') # Convierte edad en formato numero
df_clientes_mod.loc[(df_clientes_mod['edad']<0)|(df_clientes_mod['edad']>100),'edad']=np.nan

df_clientes_mod['frecuencia_visita'] = pd.to_numeric(df_clientes_mod['frecuencia_visita'], errors='coerce') # Convierte frecuencia en formato numero
df_clientes_mod.loc[df_clientes_mod['frecuencia_visita']<0,'frecuencia_visita']=np.nan

## **4. Comprobación de arreglos hechos hasta el momento desde estadística base**

In [7]:
display(df_clientes_mod['edad'].describe())
display(df_clientes_mod['frecuencia_visita'].describe())

count    29692.000000
mean        48.916173
std         18.160132
min         18.000000
25%         33.000000
50%         49.000000
75%         65.000000
max         80.000000
Name: edad, dtype: float64

count    28453.000000
mean         4.271079
std          2.279979
min          0.000000
25%          3.000000
50%          4.000000
75%          6.000000
max         10.000000
Name: frecuencia_visita, dtype: float64

## **5. Análisis de sensibilidad para variable cuantitativa**

In [8]:
promedio_edad = df_clientes_mod.groupby('consume_licor')['edad'].mean().reset_index()
display(promedio_edad)

  consume_licor       edad
0            No  53.640676
1            Sí  45.987233

## **6. Reemplazamos datos vacíos por media o moda según variable de análisis**

In [9]:
# Relleno de la edad con la media según el consumo de licor
df_clientes_mod['edad'] = df_clientes_mod['edad'].fillna(df_clientes_mod.groupby('consume_licor')['edad'].transform('mean')).round().astype(int) # La edad debe ser un número entero

# Relleno de la frecuencia de visita con la media según el estrato socioeconómico
df_clientes_mod['frecuencia_visita'] = df_clientes_mod['frecuencia_visita'].fillna(df_clientes_mod.groupby('estrato_socioeconomico')['frecuencia_visita'].transform('mean')).round().astype(int) # La frecuencia debe ser un número entero

# Relleno del promedio de gasto con la media según el estrato socioeconómico
df_clientes_mod['promedio_gasto_comida'] = df_clientes_mod['promedio_gasto_comida'].fillna(df_clientes_mod.groupby('estrato_socioeconomico')['promedio_gasto_comida'].transform('mean')).round(2) # El gasto es dinero, se deja en 2 decimales

## **7. Comprobación de datos completos**

In [10]:
df_clientes_mod[['edad', 'frecuencia_visita', 'promedio_gasto_comida']].info()

<class 'pandas.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 3 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   edad                   30000 non-null  int64
 1   frecuencia_visita      30000 non-null  int64
 2   promedio_gasto_comida  30000 non-null  float64
dtypes: float64(1), int64(2)
memory usage: 703.3 KB

## **8. Análisis de sensibilidad para variable cualitativa**

In [11]:
conteo_ciudad = df_clientes_mod.groupby(['ciudad_residencia','preferencias_alimenticias'])['preferencias_alimenticias'].size().reset_index(name='conteo')
mas_frecuente = conteo_ciudad.loc[conteo_ciudad.groupby('ciudad_residencia')['conteo'].idxmax()]
display(mas_frecuente)

   ciudad_residencia preferencias_alimenticias  conteo
5             Boston               Vegetariano     708
6            Chicago                    Carnes    1589
12            Dallas                    Carnes     822
18            Denver                    Carnes     632
24           Houston                    Carnes     716
31             Miami                  Mariscos     819
36               NYC                    Carnes    1513
42           Phoenix                    Carnes     416
53         San Diego               Vegetariano     756
59           Seattle               Vegetariano     551

## **9. Relleno de datos con NA para correo y eliminación de columnas innecesarias**

In [12]:
df_clientes_mod['correo_electronico'] = df_clientes_mod['correo_electronico'].fillna("NA")

# Se rellenan también los demás datos cualitativos que quedaron vacíos
df_clientes_mod['telefono_contacto'] = df_clientes_mod['telefono_contacto'].fillna("NA")
df_clientes_mod['preferencias_alimenticias'] = df_clientes_mod['preferencias_alimenticias'].fillna("NA")

# Eliminación de las columnas generadas en el análisis inicial que no son necesarias
df_clientes_mod = df_clientes_mod.drop(['Rango_Edad', 'Rango_Frecuencia'], axis=1)

## **10. Verificación final de la base de datos limpia**

In [13]:
display(df_clientes_mod.head())
display(df_clientes_mod.info())
display(df_clientes_mod.describe())

,id_persona,nombre,apellido,edad,genero,ciudad_residencia,estrato_socioeconomico,frecuencia_visita,promedio_gasto_comida,ocio,consume_licor,preferencias_alimenticias,membresia_premium,telefono_contacto,correo_electronico,tipo_de_pago_mas_usado,ingresos_mensuales
0,2550327378,Jackson,Gomez,31,Masculino,Miami,Alto,6,67.51,Sí,No,Vegetariano,Sí,(830)220-1926,NA,Efectivo,6425
1,9446112038,Samantha,Soto,40,Femenino,Denver,Medio,2,44.92,Sí,Sí,Mariscos,No,881-476-1426,NA,Efectivo,2374
2,3098363243,Terry,Adams,62,Femenino,Denver,Bajo,2,9.24,Sí,Sí,Vegetariano,No,NA,diana74@example.net,Efectivo,1110
3,4013002847,James,Shannon,41,Masculino,Boston,Alto,5,30.74,Sí,Sí,Carnes,Sí,NA,scottfrey@example.com,Tarjeta,6931
4,7372911048,Susan,Jones,49,Femenino,San Diego,Bajo,0,0.00,No,No,Carnes,No,243.248.8919,glassgary@example.org,Tarjeta,1350

<class 'pandas.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 17 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   id_persona                 30000 non-null  int64
 1   nombre                     30000 non-null  str
 2   apellido                   30000 non-null  str
 3   edad                       30000 non-null  int64
 4   genero                     30000 non-null  str
 5   ciudad_residencia          30000 non-null  str
 6   estrato_socioeconomico     30000 non-null  str
 7   frecuencia_visita          30000 non-null  int64
 8   promedio_gasto_comida      30000 non-null  float64
 9   ocio                       30000 non-null  str
 10  consume_licor              30000 non-null  str
 11  preferencias_alimenticias  30000 non-null  str
 12  membresia_premium          30000 non-null  str
 13  telefono_contacto          30000 non-null  str
 14  correo_electronico         30000 non-null  str
 15  tipo_de_pago_mas_usado     30000 non-null  str
 16  ingresos_mensuales         30000 non-null  int64
dtypes: float64(1), int64(4), str(12)
memory usage: 3.9 MB

None

,id_persona,edad,frecuencia_visita,promedio_gasto_comida,ingresos_mensuales
count,3.000000e+04,30000.000000,30000.000000,30000.000000,30000.000000
mean,5.504765e+09,48.927300,4.262533,32.605978,5389.755867
std,2.602799e+09,18.071542,2.255079,26.361862,4538.491728
min,1.000153e+09,18.000000,0.000000,0.000000,800.000000
25%,3.243617e+09,33.000000,3.000000,13.310000,1860.000000
50%,5.515865e+09,49.000000,4.000000,25.520000,3402.000000
75%,7.754426e+09,64.000000,5.000000,44.342500,7761.000000
max,9.999627e+09,80.000000,10.000000,149.970000,17999.000000

## **11. Guardado base de datos final para trabajar**

In [14]:
import os
os.makedirs(r'..\Data-Limpia', exist_ok=True) # Crea la carpeta Data-Limpia si no existe
df_clientes_mod.to_csv(r'..\Data-Limpia\clientes_final.csv', index=False)
print("Base de datos limpia guardada en: Data-Limpia\\clientes_final.csv")

Base de datos limpia guardada en: Data-Limpia\clientes_final.csv